name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cette ligne est importante pour autoriser les mises à jour
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build application
        run: npm run build

      - name: Verify build output
        run: |
          ls -la out  # Vérifiez que le dossier 'out' contient les fichiers générés

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out  # Le dossier contenant les fichiers générés par Next.js
          branch: gh-pages  # La branche où seront déployés les fichiers statiques